# Generated by Django 4.1.3 on 2024-01-22 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"verbose_name": "Доска", "verbose_name_plural": "Доски"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={"verbose_name": "Тред", "verbose_name_plural": "Треды"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "Тема", "verbose_name_plural": "Темы"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="hometown",
        ),
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="user",
            name="present_location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.AlterField(
            model_name="board",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="board",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="board.topic",
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="post",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="board.thread",
                verbose_name="Тред",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="board.board",
                verbose_name="Доска",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Заблокирована"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="users/%Y/%m/%d/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=64, unique=True, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=64, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=64,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_administrator",
            field=models.BooleanField(default=False, verbose_name="Администратор"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="Забанен"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_moderator",
            field=models.BooleanField(default=False, verbose_name="Модератор"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=64, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=128, verbose_name="Имя пользователя"),
        ),
    ]
